- name: Install keychain
  package:
    name: keychain
    state: present
  become: true

- name: Create `~/.keychain/`
  file:
    state: directory
    path: ~/.keychain/

- name: Add init block
  blockinfile:
    path: "{{ keychain_login_file }}"
    insertafter: EOF
    state: present
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      /usr/bin/keychain {{ keychain_args }}
      . ~/.keychain/$HOSTNAME-{{ keychain_used_shell }}
  notify:
    - "{{ role_name }} : Start keychain"
