---

- name: Ensure keychain is absent
  apt:
    name: keychain
    state: absent
  become: true

- name: Ensure init block is absent in '{{ login_file }}'
  blockinfile:
    path: "{{ login_file }}"
    insertafter: EOF
    state: absent
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: role=trallnag.keychain feead09a-b599-11eb-af8a-00155d2fcd36"
    block: |
      (/usr/bin/keychain --quick --quiet --timeout {{ timeout_minutes }} &)
      source ~/.keychain/$HOSTNAME-sh
