- name: Ensure keychain is present
  apt:
    name: keychain
    state: present
  become: true

- name: Ensure init block is present in `{{ login_file }}`
  blockinfile:
    path: "{{ login_file }}"
    insertafter: EOF
    state: present
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: role=trallnag.keychain feead09a-b599-11eb-af8a-00155d2fcd36"
    block: |
      /usr/bin/keychain {{ keychain_args }}
      source ~/.keychain/$HOSTNAME-{{ used_shell }}
  notify:
    - handler-source (trallnag.endlessh)

- name: Ensure `~/.keychain/` is present
  file:
    state: directory
    path: ~/.keychain/
